project:
  type: website
  render:
    - "*.qmd"
    - "practicas/*.qmd"
  resources:
    - "resources/**/*"
  post-render:
    - scripts/build-practice-tex.py
  preview:
    port: 3000
    browser: true

format:
  html:
    css: 
      - styles.css
    toc: true
    theme: 
      light: cosmo
    include-after-body: scripts/cookie-consent-custom.html

website:
  title: "Informática (30717) - Grado en Estudios en Arquitectura"
  description: "Material de prácticas del curso 2025-2026."
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    background: primary
    search: true
    right:
      - href: https://moodle.unizar.es/add/course/view.php?id=153600
        text: "![](../resources/unizar_white.png){width=95px}"
  sidebar:
    style: floating
    logo: ../resources/unizar.png
  page-footer:
    left: |
      © 2026 F. Bobillo, A. López, I. Huitzil, Y. Toca 
      Universidad de Zaragoza
    right: |
      Material docente protegido.  
      Licencia **CC BY-NC-SA 4.0** ![](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png){width=80px}  
      Uso docente no comercial permitido con atribución y licencia compartida.
  google-analytics:
    tracking-id: "G-KJSTYN212D"
    anonymize-ip: true
    storage: cookies
  cookie-consent:
    type: express
    style: headline
    palette: light
    language: es
    policy-url: cookies.html
    prefs-text: "Preferencias de cookies"

license: "CC BY-NC-SA 4.0"

execute:
  freeze: auto

metadata-files:
  - sidebar.yml

lang: es
